// Generated by gencpp from file ucl_drone/KeyPoint.msg
// DO NOT EDIT!


#ifndef UCL_DRONE_MESSAGE_KEYPOINT_H
#define UCL_DRONE_MESSAGE_KEYPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace ucl_drone
{
template <class ContainerAllocator>
struct KeyPoint_
{
  typedef KeyPoint_<ContainerAllocator> Type;

  KeyPoint_()
    : point()
    , descriptor()  {
    }
  KeyPoint_(const ContainerAllocator& _alloc)
    : point(_alloc)
    , descriptor(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _point_type;
  _point_type point;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _descriptor_type;
  _descriptor_type descriptor;




  typedef boost::shared_ptr< ::ucl_drone::KeyPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ucl_drone::KeyPoint_<ContainerAllocator> const> ConstPtr;

}; // struct KeyPoint_

typedef ::ucl_drone::KeyPoint_<std::allocator<void> > KeyPoint;

typedef boost::shared_ptr< ::ucl_drone::KeyPoint > KeyPointPtr;
typedef boost::shared_ptr< ::ucl_drone::KeyPoint const> KeyPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ucl_drone::KeyPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ucl_drone::KeyPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ucl_drone

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'ucl_drone': ['/home/laboinmastudent/Bureau/Drone_thesis_2017/Code/src/ucl_drone/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'ardrone_autonomy': ['/home/laboinmastudent/Bureau/Drone_thesis_2017/Additional_packages/src/ardrone_autonomy/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ucl_drone::KeyPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ucl_drone::KeyPoint_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ucl_drone::KeyPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ucl_drone::KeyPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ucl_drone::KeyPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ucl_drone::KeyPoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ucl_drone::KeyPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7471b927bc69af15f0d7edb3ca7158f8";
  }

  static const char* value(const ::ucl_drone::KeyPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7471b927bc69af15ULL;
  static const uint64_t static_value2 = 0xf0d7edb3ca7158f8ULL;
};

template<class ContainerAllocator>
struct DataType< ::ucl_drone::KeyPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ucl_drone/KeyPoint";
  }

  static const char* value(const ::ucl_drone::KeyPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ucl_drone::KeyPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
geometry_msgs/Point point\n\
float32[] descriptor # float 32 ?\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::ucl_drone::KeyPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ucl_drone::KeyPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.point);
      stream.next(m.descriptor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KeyPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ucl_drone::KeyPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ucl_drone::KeyPoint_<ContainerAllocator>& v)
  {
    s << indent << "point: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.point);
    s << indent << "descriptor[]" << std::endl;
    for (size_t i = 0; i < v.descriptor.size(); ++i)
    {
      s << indent << "  descriptor[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.descriptor[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UCL_DRONE_MESSAGE_KEYPOINT_H
