// Generated by gencpp from file ucl_drone/DroneRoles.msg
// DO NOT EDIT!


#ifndef UCL_DRONE_MESSAGE_DRONEROLES_H
#define UCL_DRONE_MESSAGE_DRONEROLES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ucl_drone/DroneRole.h>

namespace ucl_drone
{
template <class ContainerAllocator>
struct DroneRoles_
{
  typedef DroneRoles_<ContainerAllocator> Type;

  DroneRoles_()
    : roles()  {
    }
  DroneRoles_(const ContainerAllocator& _alloc)
    : roles(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::ucl_drone::DroneRole_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ucl_drone::DroneRole_<ContainerAllocator> >::other >  _roles_type;
  _roles_type roles;




  typedef boost::shared_ptr< ::ucl_drone::DroneRoles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ucl_drone::DroneRoles_<ContainerAllocator> const> ConstPtr;

}; // struct DroneRoles_

typedef ::ucl_drone::DroneRoles_<std::allocator<void> > DroneRoles;

typedef boost::shared_ptr< ::ucl_drone::DroneRoles > DroneRolesPtr;
typedef boost::shared_ptr< ::ucl_drone::DroneRoles const> DroneRolesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ucl_drone::DroneRoles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ucl_drone::DroneRoles_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ucl_drone

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'ucl_drone': ['/home/laboinmastudent/Bureau/TFE_Alex_Arnaud/ucl_drone_ws/src/ucl_drone/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'ardrone_autonomy': ['/home/laboinmastudent/Bureau/TFE_Alex_Arnaud/ucl_drone_ws/src/ardrone_autonomy/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ucl_drone::DroneRoles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ucl_drone::DroneRoles_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ucl_drone::DroneRoles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ucl_drone::DroneRoles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ucl_drone::DroneRoles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ucl_drone::DroneRoles_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ucl_drone::DroneRoles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "28014a7bc2067361e079b10f5ccfb8ba";
  }

  static const char* value(const ::ucl_drone::DroneRoles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x28014a7bc2067361ULL;
  static const uint64_t static_value2 = 0xe079b10f5ccfb8baULL;
};

template<class ContainerAllocator>
struct DataType< ::ucl_drone::DroneRoles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ucl_drone/DroneRoles";
  }

  static const char* value(const ::ucl_drone::DroneRoles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ucl_drone::DroneRoles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
# This message contains a list of all the current drone roles, formulated by the\n\
# multi-agent strategy and read by each drone's IA.\n\
\n\
# Role list\n\
ucl_drone/DroneRole[] roles\n\
\n\
================================================================================\n\
MSG: ucl_drone/DroneRole\n\
\n\
# This message contains the object drone role, formulated by the multi-agent\n\
# strategy and read by each drone's IA.\n\
\n\
# Drone name\n\
string name\n\
\n\
# Role code\n\
float64 role\n\
\n\
# List of input-output topic names. Refer to the role code for convention about\n\
# the specific use of each field\n\
string[] params\n\
";
  }

  static const char* value(const ::ucl_drone::DroneRoles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ucl_drone::DroneRoles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DroneRoles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ucl_drone::DroneRoles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ucl_drone::DroneRoles_<ContainerAllocator>& v)
  {
    s << indent << "roles[]" << std::endl;
    for (size_t i = 0; i < v.roles.size(); ++i)
    {
      s << indent << "  roles[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ucl_drone::DroneRole_<ContainerAllocator> >::stream(s, indent + "    ", v.roles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UCL_DRONE_MESSAGE_DRONEROLES_H
