# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ucl_drone/TargetDetected.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import ucl_drone.msg
import ardrone_autonomy.msg
import std_msgs.msg

class TargetDetected(genpy.Message):
  _md5sum = "615a44da705823f9b18728cd0ad9c1aa"
  _type = "ucl_drone/TargetDetected"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """
Header header
Pose3D pose
ardrone_autonomy/Navdata navdata # to be removed later
geometry_msgs/Point img_point
geometry_msgs/Point world_point

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: ucl_drone/Pose3D

# This represents an estimate of a position and velocity in 3D space.
# The pose in this message should be specified in an absolute coordinate frame.

# ucl definition of a pose message.
# TODO: unites?
# Also add velocities for the controller purpose.
# TODO: why exclude acceleration?

Header header

float64 x
float64 y
float64 z

#float64 quatX
#float64 quatY
#float64 quatZ
#float64 quatW

float64 rotX
float64 rotY
float64 rotZ

float64 xvel
float64 yvel
float64 zvel

float64 rotXvel
float64 rotYvel
float64 rotZvel

================================================================================
MSG: ardrone_autonomy/Navdata
Header header

# Navdata including the ARDrone 2 specifica sensors
# (magnetometer, barometer)

# 0 means no battery, 100 means full battery
float32 batteryPercent

# 0: Unknown, 1: Init, 2: Landed, 3: Flying, 4: Hovering, 5: Test
# 6: Taking off, 7: Goto Fix Point, 8: Landing, 9: Looping
# Note: 3,7 seems to discriminate type of flying (isFly = 3 | 7)
uint32 state

int32 magX
int32 magY
int32 magZ

# pressure sensor
int32 pressure

# apparently, there was a temperature sensor added as well.
int32 temp

# wind sensing...
float32 wind_speed
float32 wind_angle
float32 wind_comp_angle

# left/right tilt in degrees (rotation about the X axis)
float32 rotX

# forward/backward tilt in degrees (rotation about the Y axis)
float32 rotY

# orientation in degrees (rotation about the Z axis)
float32 rotZ

# estimated altitude (cm)
int32 altd

# linear velocity (mm/sec)
float32 vx

# linear velocity (mm/sec)
float32 vy

# linear velocity (mm/sec)
float32 vz

#linear accelerations (unit: g)
float32 ax
float32 ay
float32 az

#motor commands (unit 0 to 255)
uint8 motor1
uint8 motor2
uint8 motor3
uint8 motor4

#Tags in Vision Detectoion
uint32 tags_count
uint32[] tags_type
uint32[] tags_xc
uint32[] tags_yc
uint32[] tags_width
uint32[] tags_height
float32[] tags_orientation
float32[] tags_distance

#time stamp
float32 tm

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['header','pose','navdata','img_point','world_point']
  _slot_types = ['std_msgs/Header','ucl_drone/Pose3D','ardrone_autonomy/Navdata','geometry_msgs/Point','geometry_msgs/Point']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,pose,navdata,img_point,world_point

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TargetDetected, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.pose is None:
        self.pose = ucl_drone.msg.Pose3D()
      if self.navdata is None:
        self.navdata = ardrone_autonomy.msg.Navdata()
      if self.img_point is None:
        self.img_point = geometry_msgs.msg.Point()
      if self.world_point is None:
        self.world_point = geometry_msgs.msg.Point()
    else:
      self.header = std_msgs.msg.Header()
      self.pose = ucl_drone.msg.Pose3D()
      self.navdata = ardrone_autonomy.msg.Navdata()
      self.img_point = geometry_msgs.msg.Point()
      self.world_point = geometry_msgs.msg.Point()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.pose.header.seq, _x.pose.header.stamp.secs, _x.pose.header.stamp.nsecs))
      _x = self.pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_12d3I.pack(_x.pose.x, _x.pose.y, _x.pose.z, _x.pose.rotX, _x.pose.rotY, _x.pose.rotZ, _x.pose.xvel, _x.pose.yvel, _x.pose.zvel, _x.pose.rotXvel, _x.pose.rotYvel, _x.pose.rotZvel, _x.navdata.header.seq, _x.navdata.header.stamp.secs, _x.navdata.header.stamp.nsecs))
      _x = self.navdata.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_fI5i6fi6f4BI.pack(_x.navdata.batteryPercent, _x.navdata.state, _x.navdata.magX, _x.navdata.magY, _x.navdata.magZ, _x.navdata.pressure, _x.navdata.temp, _x.navdata.wind_speed, _x.navdata.wind_angle, _x.navdata.wind_comp_angle, _x.navdata.rotX, _x.navdata.rotY, _x.navdata.rotZ, _x.navdata.altd, _x.navdata.vx, _x.navdata.vy, _x.navdata.vz, _x.navdata.ax, _x.navdata.ay, _x.navdata.az, _x.navdata.motor1, _x.navdata.motor2, _x.navdata.motor3, _x.navdata.motor4, _x.navdata.tags_count))
      length = len(self.navdata.tags_type)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(struct.pack(pattern, *self.navdata.tags_type))
      length = len(self.navdata.tags_xc)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(struct.pack(pattern, *self.navdata.tags_xc))
      length = len(self.navdata.tags_yc)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(struct.pack(pattern, *self.navdata.tags_yc))
      length = len(self.navdata.tags_width)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(struct.pack(pattern, *self.navdata.tags_width))
      length = len(self.navdata.tags_height)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(struct.pack(pattern, *self.navdata.tags_height))
      length = len(self.navdata.tags_orientation)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.navdata.tags_orientation))
      length = len(self.navdata.tags_distance)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.pack(pattern, *self.navdata.tags_distance))
      _x = self
      buff.write(_struct_f6d.pack(_x.navdata.tm, _x.img_point.x, _x.img_point.y, _x.img_point.z, _x.world_point.x, _x.world_point.y, _x.world_point.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.pose is None:
        self.pose = ucl_drone.msg.Pose3D()
      if self.navdata is None:
        self.navdata = ardrone_autonomy.msg.Navdata()
      if self.img_point is None:
        self.img_point = geometry_msgs.msg.Point()
      if self.world_point is None:
        self.world_point = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.pose.header.seq, _x.pose.header.stamp.secs, _x.pose.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pose.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 108
      (_x.pose.x, _x.pose.y, _x.pose.z, _x.pose.rotX, _x.pose.rotY, _x.pose.rotZ, _x.pose.xvel, _x.pose.yvel, _x.pose.zvel, _x.pose.rotXvel, _x.pose.rotYvel, _x.pose.rotZvel, _x.navdata.header.seq, _x.navdata.header.stamp.secs, _x.navdata.header.stamp.nsecs,) = _struct_12d3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.navdata.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.navdata.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 88
      (_x.navdata.batteryPercent, _x.navdata.state, _x.navdata.magX, _x.navdata.magY, _x.navdata.magZ, _x.navdata.pressure, _x.navdata.temp, _x.navdata.wind_speed, _x.navdata.wind_angle, _x.navdata.wind_comp_angle, _x.navdata.rotX, _x.navdata.rotY, _x.navdata.rotZ, _x.navdata.altd, _x.navdata.vx, _x.navdata.vy, _x.navdata.vz, _x.navdata.ax, _x.navdata.ay, _x.navdata.az, _x.navdata.motor1, _x.navdata.motor2, _x.navdata.motor3, _x.navdata.motor4, _x.navdata.tags_count,) = _struct_fI5i6fi6f4BI.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      end += struct.calcsize(pattern)
      self.navdata.tags_type = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      end += struct.calcsize(pattern)
      self.navdata.tags_xc = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      end += struct.calcsize(pattern)
      self.navdata.tags_yc = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      end += struct.calcsize(pattern)
      self.navdata.tags_width = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      end += struct.calcsize(pattern)
      self.navdata.tags_height = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.navdata.tags_orientation = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.navdata.tags_distance = struct.unpack(pattern, str[start:end])
      _x = self
      start = end
      end += 52
      (_x.navdata.tm, _x.img_point.x, _x.img_point.y, _x.img_point.z, _x.world_point.x, _x.world_point.y, _x.world_point.z,) = _struct_f6d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.pose.header.seq, _x.pose.header.stamp.secs, _x.pose.header.stamp.nsecs))
      _x = self.pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_12d3I.pack(_x.pose.x, _x.pose.y, _x.pose.z, _x.pose.rotX, _x.pose.rotY, _x.pose.rotZ, _x.pose.xvel, _x.pose.yvel, _x.pose.zvel, _x.pose.rotXvel, _x.pose.rotYvel, _x.pose.rotZvel, _x.navdata.header.seq, _x.navdata.header.stamp.secs, _x.navdata.header.stamp.nsecs))
      _x = self.navdata.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_fI5i6fi6f4BI.pack(_x.navdata.batteryPercent, _x.navdata.state, _x.navdata.magX, _x.navdata.magY, _x.navdata.magZ, _x.navdata.pressure, _x.navdata.temp, _x.navdata.wind_speed, _x.navdata.wind_angle, _x.navdata.wind_comp_angle, _x.navdata.rotX, _x.navdata.rotY, _x.navdata.rotZ, _x.navdata.altd, _x.navdata.vx, _x.navdata.vy, _x.navdata.vz, _x.navdata.ax, _x.navdata.ay, _x.navdata.az, _x.navdata.motor1, _x.navdata.motor2, _x.navdata.motor3, _x.navdata.motor4, _x.navdata.tags_count))
      length = len(self.navdata.tags_type)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(self.navdata.tags_type.tostring())
      length = len(self.navdata.tags_xc)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(self.navdata.tags_xc.tostring())
      length = len(self.navdata.tags_yc)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(self.navdata.tags_yc.tostring())
      length = len(self.navdata.tags_width)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(self.navdata.tags_width.tostring())
      length = len(self.navdata.tags_height)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(self.navdata.tags_height.tostring())
      length = len(self.navdata.tags_orientation)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.navdata.tags_orientation.tostring())
      length = len(self.navdata.tags_distance)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.navdata.tags_distance.tostring())
      _x = self
      buff.write(_struct_f6d.pack(_x.navdata.tm, _x.img_point.x, _x.img_point.y, _x.img_point.z, _x.world_point.x, _x.world_point.y, _x.world_point.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.pose is None:
        self.pose = ucl_drone.msg.Pose3D()
      if self.navdata is None:
        self.navdata = ardrone_autonomy.msg.Navdata()
      if self.img_point is None:
        self.img_point = geometry_msgs.msg.Point()
      if self.world_point is None:
        self.world_point = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.pose.header.seq, _x.pose.header.stamp.secs, _x.pose.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pose.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 108
      (_x.pose.x, _x.pose.y, _x.pose.z, _x.pose.rotX, _x.pose.rotY, _x.pose.rotZ, _x.pose.xvel, _x.pose.yvel, _x.pose.zvel, _x.pose.rotXvel, _x.pose.rotYvel, _x.pose.rotZvel, _x.navdata.header.seq, _x.navdata.header.stamp.secs, _x.navdata.header.stamp.nsecs,) = _struct_12d3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.navdata.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.navdata.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 88
      (_x.navdata.batteryPercent, _x.navdata.state, _x.navdata.magX, _x.navdata.magY, _x.navdata.magZ, _x.navdata.pressure, _x.navdata.temp, _x.navdata.wind_speed, _x.navdata.wind_angle, _x.navdata.wind_comp_angle, _x.navdata.rotX, _x.navdata.rotY, _x.navdata.rotZ, _x.navdata.altd, _x.navdata.vx, _x.navdata.vy, _x.navdata.vz, _x.navdata.ax, _x.navdata.ay, _x.navdata.az, _x.navdata.motor1, _x.navdata.motor2, _x.navdata.motor3, _x.navdata.motor4, _x.navdata.tags_count,) = _struct_fI5i6fi6f4BI.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      end += struct.calcsize(pattern)
      self.navdata.tags_type = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      end += struct.calcsize(pattern)
      self.navdata.tags_xc = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      end += struct.calcsize(pattern)
      self.navdata.tags_yc = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      end += struct.calcsize(pattern)
      self.navdata.tags_width = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      end += struct.calcsize(pattern)
      self.navdata.tags_height = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.navdata.tags_orientation = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      end += struct.calcsize(pattern)
      self.navdata.tags_distance = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      _x = self
      start = end
      end += 52
      (_x.navdata.tm, _x.img_point.x, _x.img_point.y, _x.img_point.z, _x.world_point.x, _x.world_point.y, _x.world_point.z,) = _struct_f6d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_fI5i6fi6f4BI = struct.Struct("<fI5i6fi6f4BI")
_struct_3I = struct.Struct("<3I")
_struct_f6d = struct.Struct("<f6d")
_struct_12d3I = struct.Struct("<12d3I")
